services:
  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - sail
    restart: unless-stopped

  scheduler:
    build: .
    command: python3 scheduler.py
    networks:
      - sail

networks:
  sail:
    external: true